// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import "@vue/runtime-core";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AButton: typeof import("ant-design-vue/es")["Button"];
    ADatePicker: typeof import("ant-design-vue/es")["DatePicker"];
    LxAlert: typeof import("./src/components/lx-alert.vue")["default"];
    LxIcon: typeof import("./src/components/lx-icon.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}

export {};
